In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Online_Retail_Cleaned.csv")

In [3]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Year,Month,Day,Hour
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,2010,12,1,8
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2010,12,1,8
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,2010,12,1,8
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2010,12,1,8
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2010,12,1,8

In [4]:
df.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Year,Month,Day,Hour
392727,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,2011,12,9,12
392728,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,2011,12,9,12
392729,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,2011,12,9,12
392730,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,2011,12,9,12
392731,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,2011,12,9,12

In [5]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

In [6]:
df.dtypes

InvoiceNo               int64
StockCode                 str
Description               str
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID            float64
Country                   str
Year                    int64
Month                   int64
Day                     int64
Hour                    int64
dtype: object

In [7]:
# ab hum na aik column bannaye ga jis ma hum Revenus nikale ga
df["Revenue"] = df["Quantity"] * df["UnitPrice"]

In [8]:
# ab is ki head show karaye ga
df[["Quantity", "UnitPrice", "Revenue"]].head()

   Quantity  UnitPrice  Revenue
0         6       2.55    15.30
1         6       3.39    20.34
2         8       2.75    22.00
3         6       3.39    20.34
4         6       3.39    20.34

In [10]:
# ab poore dataset ka revenus nikale ga
df["Revenue"].sum()
# # ab poore dataset ka revenus ka mean, mode, median
df["Revenue"].describe()

count    392732.000000
mean         22.629195
std         311.083465
min           0.000000
25%           4.950000
50%          12.390000
75%          19.800000
max      168469.600000
Name: Revenue, dtype: float64

In [ ]:
# import pandas as pd

# df = pd.read_csv("Online_Retail_Cleaned.csv")

# df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

# df["Revenue"] = df["Quantity"] * df["UnitPrice"]

# df[["Quantity", "UnitPrice", "Revenue"]].head()

   Quantity  UnitPrice  Revenue
0         6       2.55    15.30
1         6       3.39    20.34
2         8       2.75    22.00
3         6       3.39    20.34
4         6       3.39    20.34

In [12]:
# poore dataset ka revenue nikalo
total_revenue = df["Revenue"].sum()

print("Total Revenue:", total_revenue)

Total Revenue: 8887208.894

In [13]:
# average transaction revenue:
average_revenue = df["Revenue"].mean()

print("Average Revenue:", average_revenue)

Average Revenue: 22.629194702748947

In [14]:
max_revenue = df["Revenue"].max()

print("Maximum Revenue:", max_revenue)

Maximum Revenue: 168469.6

In [15]:
df["YearMonth"] = df["InvoiceDate"].dt.to_period("M")

In [16]:
df[["InvoiceDate", "YearMonth"]].head()

          InvoiceDate YearMonth
0 2010-12-01 08:26:00   2010-12
1 2010-12-01 08:26:00   2010-12
2 2010-12-01 08:26:00   2010-12
3 2010-12-01 08:26:00   2010-12
4 2010-12-01 08:26:00   2010-12

In [18]:
df["DayName"] = df["InvoiceDate"].dt.day_name()
df[["InvoiceDate", "DayName"]].head()

          InvoiceDate    DayName
0 2010-12-01 08:26:00  Wednesday
1 2010-12-01 08:26:00  Wednesday
2 2010-12-01 08:26:00  Wednesday
3 2010-12-01 08:26:00  Wednesday
4 2010-12-01 08:26:00  Wednesday

In [ ]:
# Invoice Total
# .Invoice Total banate hain. Isse pata chalega ke ek complete invoice/order ki total sale kitni thi.
invoice_totals = df.groupby("InvoiceNo")["Revenue"].sum()
invoice_totals.head()

InvoiceNo
536365    139.12
536366     22.20
536367    278.73
536368     70.05
536369     17.85
Name: Revenue, dtype: float64

In [20]:
# Customer Total
# Isse pata chalega ke har customer ne total kitni revenue generate ki.
customer_totals = df.groupby("CustomerID")["Revenue"].sum()
customer_totals.head()

CustomerID
12346.0    77183.60
12347.0     4310.00
12348.0     1797.24
12349.0     1757.55
12350.0      334.40
Name: Revenue, dtype: float64